sudo: required
language: go

go:
  - "1.9"
  - "1.10"
  - master

services:
  - docker

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/gobuffalo/packr/...

install:
  - make test-ci
  - make install
  - make post
