version: '2'

services:
  mysql:
    container_name: modelgen-tests
    image: mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
      - "3307:3306"